Vagrant.configure("2") do |c|
  c.vm.define 'ubuntu-server-12042-x64' do |v|
    v.vm.hostname = 'ubuntu-server-12042-x64'
    v.vm.box = 'ubuntu-server-12042-x64-vbox4210-nocm'
    v.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box'
    v.vm.base_mac = '0800276654AD'
    v.vm.network :private_network, ip: "10.255.95.127", :netmask => "255.255.0.0"
  end
  c.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
